# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1cae4418bfb2de650ece4f6fa816c74f7ca0343a687e184436d2d21571221c8481ab4261bce8ee9bf672ec14dd29d9b31bf07389ab3c2e2cdb52ac70ffe696

test:
  secret_key_base: af231d8b1e2280c47d40f7649422f6fda52f13f0cb401392aca25eb409dab1925a68a10a65480a1c26acc21d2287c674064fd3092660913833a44a69711df0fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
